name: Building

on: [ push, pull_request ]

jobs:
  Build-Wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
        os: [ubuntu-20.04, macos-latest]

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Print Python info
        run: |
          which python${{ matrix.python-version }}
          python${{ matrix.python-version }} --version

      - name: Install dependencies (macos)
        if: matrix.os == 'macos-latest'
        run: |
          brew install laszip ninja
          python${{ matrix.python-version }} -m pip install wheel pybind11

      - name: Install dependencies (ubuntu)
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt install ninja-build liblaszip-dev
          python${{ matrix.python-version }}  -m pip install wheel pybind11

      - name: Build Wheel
        run: python${{ matrix.python-version }} setup.py bdist_wheel

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.os }}-${{ matrix.python-version }}"
          path: "./dist/*.whl"
