name: Building

on: [ push, pull_request ]

jobs:
  Build-ManyLinux-Wheels:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build Wheel
        run: docker run --rm -v `pwd`:/io -e PLAT=manylinux2014_x86_64 quay.io/pypa/manylinux2014_x86_64 /bin/sh /io/scripts/build-wheels-linux.sh

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "manylinux-wheels"
          path: "./wheelhouse/*manylinux*.whl"
